name: drink_serving_constraints
constraints:
  - type: orientation
    frame_id: base_link
    link_name: gripper_tip_link
    orientation: [0, 0, 0] #RPY
    tolerances: [0.4, 0.4, 6.28318531]
    weight: 1.0
    name: drink_orient_constraint